### PR TITLE
Fix user guide errors from #141

### LINKED ISSUE #141: User guide has some tiny errors
some tiny errors as follows:

image

image

you should specify which data you have used.
image

Is the user guide not completed？

### PR DESCRIPTION
**Pull request by cnpryer**
Fixes #141

### CODE REVIEW

**Comment by ritchie46** [comment]
Can I merge those already?

**Comment by cnpryer** [comment]
Sure!

**Comment by cnpryer** [comment]
@ritchie46 I modified the snippet area for the US Congress data too. Maybe it'll resolve some confusion from #141 and #120.

**Comment by ritchie46** [comment]
Thanks a lit @cnpryer

**Pull request merged**
