### PR TITLE
Selecting data

### PR DESCRIPTION
**Pull request by braaannigan**
Replacement section for the current Indexing. Splits it out into separate pages for an intro, expressions and indexing. Bumped it up the order so it appears before Expressions

### CODE REVIEW

**Comment by ritchie46** [comment]
Can we put ut behind expressions? I find expressions the most improtant.

**Comment by cnpryer** [comment]
I actually agree that we can ease readers into it better, and that doing so could help emphasize a topic like Expressions. But my PR for the walkthrough was kind of aimed at that.

I'm starting to think we can coordinate a broader Cookbook 2.0 proposal for organizing something like

Intro -> Getting Started -> Fundamentals -> Walkthrough -> Recipes -> References and Contributing

**Comment by ritchie46** [comment]
I am for chris' proposal::

Intro -> Getting Started -> Fundamentals -> Walkthrough -> Recipes -> References and Contributing

* The intro and getting started are short. 
* The fundamentals are the expression guide. That is most important and should make everything else click.
* walkthroughs and recipes may go in detail into things that is less important to understand polars. Such as indexing. 

I really want the intro and expression guides to be the first two chapters, after that I am more lenient. :)

**Comment by braaannigan** [comment]
Ok, I've modified the summary.md

**Comment by braaannigan** [comment]
Does it make sense to move this section to "How can I" to follow IO?

**Comment by cnpryer** [comment]
Tbh I'm not in love with "Cookbook" either but it's become a kind of buzzword. I see the value in using it, but you can end up confused as a user if you take it too literally.

My personal opinion is that we call it "The Polars Book". I like simple. But 🤷‍♂️

**Comment by braaannigan** [comment]
@ritchie46 @cnpryer 
I propose we move this section (and time series) to the How can I section? So then HCI would start with IO, then go onto selecting data, working with time series, strings, missing data etc and cross-reference the material in the expressions and fundamentals sections?

Let me know what you're thinking and I'll confirm this is ready for review asap

**Comment by ritchie46** [comment]
That sounds good to me. ,👍

**Comment by braaannigan** [comment]
Ok, i've moved selecting data, timseries and missing data to howcani.  I feel that we're on the path to the much cleaner structure @cnpryer has set out, plenty of work to go of course!

**Comment by cnpryer** [comment]
I actually thought we were throwing out "How Can I?" entirely

**Comment by braaannigan** [comment]
Ok, I meant wherever this kind of material will end up. It's not clear to me exactly what fits where

**Comment by cnpryer** [comment]
Yea I think the concept of a How Can I is good, but it's essentially the "recipe" part of a cookbook. In a 2.0 I imagine anything that falls under "how do I do X" (that's a good fit for the book) will just be a recipe after all the foundational content.

So personally I think moving them to the How Can I is perfect, but we should scrap How Can I for just a consolidated recipe section of the book.

**Comment by braaannigan** [comment]
Great

**Comment by ritchie46** [comment]
Thanks @braaannigan

**Comment by ritchie46** [comment]
Thanks for your work @braaannigan.

Not something for now, but for a next time we should create a single python file per example. This make refactoring much simpler and reduces the probability of slicing the wrong code snippets (e.g. when we remove an example snippet)

**Pull request merged**
