### PR TITLE
Adding Polars quickstart guide

### PR DESCRIPTION
**Pull request by r-brink**
Hello!

Created a first version of a Polars quickstart guide for new users. Goal is to have all the common and most used functionalities in one page to go through. I have included links to the Polars book and reference guide after every part for further reference. 

Big gap in this version of the guide is the Lazy API. I have some examples lined up, but I can use some feedback at this point to see if this is the right direction.

It is definitely not perfect, so all the feedback is more than welcome @carnarez @YuRiTan   👀

### CODE REVIEW

**Comment by braaannigan** [comment]
Nice work @r-brink!

I've just made a 10-minutes-to-polars PR. It will be good to have more introductory material. 

The content overlaps of course, but there's no harm in that. In terms of how they relate to each other I think the main thing is how to name them - perhaps my notebook could be the first in a series of tutorials while this stays as the quickstart?

**Comment by r-brink** [comment]
Thanks @braaannigan. Your notebook looks great as well. I like the additional explanations you gave in some parts.

I tried coming up with a generic name for the docs I wrote. Thought about naming it 10 minutes to as well, as it is heavily inspired by a certain 10-minutes-to tutorial. But I didn't like it that that specific tutorial was quite long and probably surpassed the 10 minute read a long time ago. Therefore I gave it the work name quick exploration guide, but it could be a quickstart as well as it covers the basics.

It is a nice idea to use yours as a foundation for additional topics. What is your idea on the series of tutorials? Do you have additional topics lined up? I think the structure of the tutorials are key to ensure that users easily find relevant information.

**Comment by braaannigan** [comment]
> Thanks @braaannigan. Your notebook looks great as well. I like the additional explanations you gave in some parts.
> 
> I tried coming up with a generic name for the docs I wrote. Thought about naming it 10 minutes to as well, as it is heavily inspired by a certain 10-minutes-to tutorial. But I didn't like it that that specific tutorial was quite long and probably surpassed the 10 minute read a long time ago. Therefore I gave it the work name quick exploration guide, but it could be a quickstart as well as it covers the basics.
> 
> It is a nice idea to use yours as a foundation for additional topics. What is your idea on the series of tutorials? Do you have additional topics lined up? I think the structure of the tutorials are key to ensure that users easily find relevant information.

I was thinking this one could be 10-minutes-to tabular, another one could be time series, another one NLP. 

I'm open to suggestions though and I'm not wedded to the whole 10-minutes conceit for the notebooks, could just call them tutorials or something

**Comment by braaannigan** [comment]
@ritchie46 Any thoughts before we get these merged?

**Comment by r-brink** [comment]
@ritchie46 I think I can fix it this month

**Comment by ritchie46** [comment]
Thanks you guys. Let's already merge it. We can fix snippets down the road.

**Pull request merged**
