### PR TITLE
Add multiprocessing guide

### PR DESCRIPTION
**Pull request by zundertj**
Should be good now.

### CODE REVIEW

**Comment by ghuls** [comment]
Probably should be updated as with the latest Polars it should be less likely to happen: https://github.com/pola-rs/polars/pull/5237/commits/c6d08e316d5eff3eb39af2e657957fd7eec0d077

**Comment by zundertj** [comment]
> Probably should be updated as with the latest Polars it should be less likely to happen: [pola-rs/polars@c6d08e3](https://github.com/pola-rs/polars/commit/c6d08e316d5eff3eb39af2e657957fd7eec0d077)

Done!

**Comment by zundertj** [comment]
Formatted again, the quick last-minute edit via the GH web ui was the culprit.

**Comment by ghuls** [comment]
@zundertj  The includes don't render it seems: https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html

**Comment by zundertj** [comment]
> @zundertj The includes don't render it seems: https://pola-rs.github.io/polars-book/user-guide/howcani/multiprocessing.html

I saw that as well, but I don't know why. Is a line select necessary for the include statement? For example, wrapped in a Python code block, I have:

```
{{#include ../../examples/multiprocessing/example1.py}}
```
which does not work.

On another page:
```
{{#include ../../examples/combining_data/vertical_concat_example.py:4:22}}
print(df_vertical_concat)
```
which does work.

Happy for anyone to chime in and fix this :)

**Pull request merged**
