### PR TITLE
Remove NodeJS from user guide

### PR DESCRIPTION
**Pull request by stinodego**
We are in the process of consolidating the user guide as part of the main repository: [#10560](https://github.com/pola-rs/polars/issues/10560).
This will allow us to version the user guide along with our Python bindings and make sure they are aligned at all times.

In doing so, we can no longer include NodeJS in the guide, as that code does not live in the main repo. Updates in the NodeJS could then break the CI of the main repo.

~We encourage community maintainers of Polars bindings to set up their own user documentation.~ Let's hold off on this for a moment while we figure out the best way to integrate community fork docs.

Feel free to ping me with any  questions.

@universalmind303 FYI - feel free to share your thoughts on this.

### CODE REVIEW

**Comment by universalmind303** [comment]
Something we could do for official community supported bindings such as node and R is expose an interface for what examples the user guide is expecting and fetch them from the repos. 

this is how meilisearch links theirs 
- [user guide](https://github.com/meilisearch/documentation). 
- [language specific impl](https://github.com/meilisearch/meilisearch-js/blob/main/.code-samples.meilisearch.yaml)

the way it works is it pulls from the repo for the given examples defined in the user guide, if they aren't available, the user guide doesn't render them. This would still require the community supported bindings to keep their documentation up to date with the user guide while also preventing them from breaking the CI. The CI could just lock to a specific tag or commit of the repo.

**Comment by stinodego** [comment]
I'll look into that, thanks!

**Comment by c-peters** [comment]
I would be in favor of supporting community supported bindings by pulling in the examples from the corresponding implementations.

To not overcomplicate things, I suggest first merging in the docs to the main repo and then building these bindings. This would temporarily remove the nodejs from the user guide, but allow us some time to figure out how to best integrate them without blocking the current User Guide issues.

**Review by c-peters — APPROVED** [review]

**Comment by stinodego** [comment]
Right, so we may include community maintained bindings in the main user guide, but we'll have to figure out a nice way to do so.

I'll go ahead with this for now to finish the integration first, as Chiel suggested.

**Pull request merged**
